In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")
df=pd.read_csv("cancer.csv")
df=df.drop(['id','Unnamed: 32'],axis=1)

In [2]:
df['texture_mean']=np.sqrt(np.sqrt(np.sqrt(df['texture_mean'])))
df['perimeter_mean']=np.log(np.log(np.log(df['perimeter_mean'])))
df['smoothness_mean']=np.sqrt(np.sqrt(np.sqrt(df['smoothness_mean'])))
df['compactness_mean']=np.log(df['compactness_mean'])
df['symmetry_mean']=np.log(df['symmetry_mean'])
df['fractal_dimension_mean']=np.log(np.sqrt(df['fractal_dimension_mean']))
df['texture_se']=np.log(df['texture_se'])
df['smoothness_se']=np.log(np.sqrt(df['smoothness_se']))
df['area_se']=np.log(np.log(np.log(df['area_se'])))
df['concave points_se']=np.sqrt(df['concave points_se'])
df['symmetry_se']=np.log(np.sqrt(df['symmetry_se']))
df['fractal_dimension_se']=np.log(np.sqrt(np.sqrt(df['fractal_dimension_se'])))

In [3]:
f_drop=['radius_worst','texture_worst','perimeter_worst','area_worst','smoothness_worst','compactness_worst',\
        'concavity_worst','concave points_worst','symmetry_worst','fractal_dimension_worst','radius_mean',\
        'concavity_se','perimeter_se','concavity_mean','area_mean','compactness_se','radius_se','concave points_mean']
df=df.drop(f_drop,axis=1)

In [4]:
from sklearn.preprocessing import LabelEncoder
le_diagnosis=LabelEncoder()
df['diagnosis_code']=le_diagnosis.fit_transform(df['diagnosis'])
df[['diagnosis','diagnosis_code']].head()

diagnosis  diagnosis_code
0         M               1
1         M               1
2         M               1
3         M               1
4         M               1

In [5]:
df.drop('diagnosis',axis=1,inplace=True)
df['diagnosis_code'].head()

0    1
1    1
2    1
3    1
4    1
Name: diagnosis_code, dtype: int32

In [6]:
X=df.drop(['diagnosis_code'],axis=1)
Y=df['diagnosis_code']

In [7]:
diagnosis_code=pd.get_dummies(df['diagnosis_code'],drop_first=True)
diagnosis_code.head()

1
0  1
1  1
2  1
3  1
4  1

In [8]:
df.diagnosis_code.value_counts()

0    357
1    212
Name: diagnosis_code, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

# Train Data With 9 Input Features

In [10]:
x=df.drop(['diagnosis_code','fractal_dimension_se','texture_se',],axis=1)
y=df.diagnosis_code

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=4)

classifier_entropy=DecisionTreeClassifier(criterion='entropy',random_state=42,max_depth=3)

classifier_entropy.fit(x_train,y_train)

predictions=classifier_entropy.predict(x_test)

r=confusion_matrix(y_test,predictions)
print(r)

[[104  13]
 [  7  47]]


In [11]:
print("accuracy:",accuracy_score(y_test,predictions)*100)
print("True Positive Rate (TPR) :",(r[0][0]/(r[0][0]+r[1][0]))*100)
print("True Negative Rate (TNR) :",(r[1][1]/(r[1][1]+r[0][1]))*100)
print("False Negative Rate (FNR) :",(r[1][0]/(r[1][0]+r[0][0]))*100)
print("False Positive Rate (FPR) :",(r[0][1]/(r[0][1]+r[1][1]))*100)
x1=(classification_report(y_test,predictions))
print(x1)

accuracy: 88.30409356725146
True Positive Rate (TPR) : 93.69369369369369
True Negative Rate (TNR) : 78.33333333333333
False Negative Rate (FNR) : 6.306306306306306
False Positive Rate (FPR) : 21.666666666666668
              precision    recall  f1-score   support

           0       0.94      0.89      0.91       117
           1       0.78      0.87      0.82        54

   micro avg       0.88      0.88      0.88       171
   macro avg       0.86      0.88      0.87       171
weighted avg       0.89      0.88      0.88       171



# Train Data With 10 Input Features

In [12]:
x=df.drop(['diagnosis_code','fractal_dimension_se','texture_se',],axis=1)
y=df.diagnosis_code

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=4)

classifier_entropy=DecisionTreeClassifier(criterion='entropy',random_state=42,max_depth=3)

classifier_entropy.fit(x_train,y_train)

predictions=classifier_entropy.predict(x_test)

r=confusion_matrix(y_test,predictions)
print(r)

[[104  13]
 [  7  47]]


In [13]:
print("accuracy:",accuracy_score(y_test,predictions)*100)
print("True Positive Rate (TPR) :",(r[0][0]/(r[0][0]+r[1][0]))*100)
print("True Negative Rate (TNR) :",(r[1][1]/(r[1][1]+r[0][1]))*100)
print("False Negative Rate (FNR) :",(r[1][0]/(r[1][0]+r[0][0]))*100)
print("False Positive Rate (FPR) :",(r[0][1]/(r[0][1]+r[1][1]))*100)
x1=(classification_report(y_test,predictions))
print(x1)

accuracy: 88.30409356725146
True Positive Rate (TPR) : 93.69369369369369
True Negative Rate (TNR) : 78.33333333333333
False Negative Rate (FNR) : 6.306306306306306
False Positive Rate (FPR) : 21.666666666666668
              precision    recall  f1-score   support

           0       0.94      0.89      0.91       117
           1       0.78      0.87      0.82        54

   micro avg       0.88      0.88      0.88       171
   macro avg       0.86      0.88      0.87       171
weighted avg       0.89      0.88      0.88       171



# Train Data With 11 Input Features

In [14]:
x=df.drop(['diagnosis_code','fractal_dimension_se'],axis=1)
y=df.diagnosis_code

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=4)

classifier_entropy=DecisionTreeClassifier(criterion='entropy',random_state=42,max_depth=3)

classifier_entropy.fit(x_train,y_train)

predictions=classifier_entropy.predict(x_test)

r=confusion_matrix(y_test,predictions)
print(r)# Train Data With 12 Variables

[[104  13]
 [  7  47]]


In [15]:
print("accuracy:",accuracy_score(y_test,predictions)*100)
print("True Positive Rate (TPR) :",(r[0][0]/(r[0][0]+r[1][0]))*100)
print("True Negative Rate (TNR) :",(r[1][1]/(r[1][1]+r[0][1]))*100)
print("False Negative Rate (FNR) :",(r[1][0]/(r[1][0]+r[0][0]))*100)
print("False Positive Rate (FPR) :",(r[0][1]/(r[0][1]+r[1][1]))*100)
x1=(classification_report(y_test,predictions))
print(x1)

accuracy: 88.30409356725146
True Positive Rate (TPR) : 93.69369369369369
True Negative Rate (TNR) : 78.33333333333333
False Negative Rate (FNR) : 6.306306306306306
False Positive Rate (FPR) : 21.666666666666668
              precision    recall  f1-score   support

           0       0.94      0.89      0.91       117
           1       0.78      0.87      0.82        54

   micro avg       0.88      0.88      0.88       171
   macro avg       0.86      0.88      0.87       171
weighted avg       0.89      0.88      0.88       171



# Train Data With 12 Input Features

In [16]:
x=df.drop(['diagnosis_code'],axis=1)
y=df.diagnosis_code

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=4)

classifier_entropy=DecisionTreeClassifier(criterion='entropy',random_state=42,max_depth=3)

classifier_entropy.fit(x_train,y_train)

predictions=classifier_entropy.predict(x_test)

r=confusion_matrix(y_test,predictions)
print(r)

[[105  12]
 [  7  47]]


In [17]:
print("accuracy:",accuracy_score(y_test,predictions)*100)
print("True Positive Rate (TPR) :",(r[0][0]/(r[0][0]+r[1][0]))*100)
print("True Negative Rate (TNR) :",(r[1][1]/(r[1][1]+r[0][1]))*100)
print("False Negative Rate (FNR) :",(r[1][0]/(r[1][0]+r[0][0]))*100)
print("False Positive Rate (FPR) :",(r[0][1]/(r[0][1]+r[1][1]))*100)
x1=(classification_report(y_test,predictions))
print(x1)

accuracy: 88.88888888888889
True Positive Rate (TPR) : 93.75
True Negative Rate (TNR) : 79.66101694915254
False Negative Rate (FNR) : 6.25
False Positive Rate (FPR) : 20.33898305084746
              precision    recall  f1-score   support

           0       0.94      0.90      0.92       117
           1       0.80      0.87      0.83        54

   micro avg       0.89      0.89      0.89       171
   macro avg       0.87      0.88      0.87       171
weighted avg       0.89      0.89      0.89       171

