In [1]:
#KNN model
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

df=pd.read_csv('Cancer.csv')
df=df.drop(['Unnamed: 32','id'], axis=1)

In [2]:
df['texture_mean']=np.sqrt(np.sqrt(np.sqrt(df['texture_mean'])))
df['perimeter_mean']=np.log(np.log(np.log(df['perimeter_mean'])))
df['smoothness_mean']=np.sqrt(np.sqrt(np.sqrt(df['smoothness_mean'])))
df['compactness_mean']=np.log(df['compactness_mean'])
df['symmetry_mean']=np.log(df['symmetry_mean'])
df['fractal_dimension_mean']=np.log(np.sqrt(df['fractal_dimension_mean']))
df['texture_se']=np.log(df['texture_se'])
df['smoothness_se']=np.log(np.sqrt(df['smoothness_se']))
df['area_se']=np.log(np.log(np.log(df['area_se'])))
df['concave points_se']=np.sqrt(df['concave points_se'])
df['symmetry_se']=np.log(np.sqrt(df['symmetry_se']))
df['fractal_dimension_se']=np.log(np.sqrt(np.sqrt(df['fractal_dimension_se'])))

In [3]:
f_drop=['radius_worst','texture_worst','perimeter_worst','area_worst','smoothness_worst','compactness_worst',\
        'concavity_worst','concave points_worst','symmetry_worst','fractal_dimension_worst','radius_mean',\
        'concavity_se','perimeter_se','concavity_mean','area_mean','compactness_se','radius_se','concave points_mean']
df=df.drop(f_drop,axis=1)

In [4]:
from sklearn.preprocessing import LabelEncoder
le_diagnosis=LabelEncoder()
df['diagnosis_code']=le_diagnosis.fit_transform(df['diagnosis'])
df.drop('diagnosis',axis=1,inplace=True)

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

# Train Data with 9 Input Features

In [6]:
x=df.drop(['diagnosis_code','fractal_dimension_se','symmetry_se','texture_se'],axis=1)
y=df.diagnosis_code

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=4,test_size=0.3)

sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

classifier=KNeighborsClassifier(n_neighbors=7,p=2,metric='euclidean')
classifier.fit(x_train,y_train)

predictions=classifier.predict(x_test)

r=confusion_matrix(y_test,predictions)
print(r)

[[107  10]
 [  1  53]]


In [7]:
print("accuracy:",accuracy_score(y_test,predictions)*100)
print("True Positive Rate (TPR) :",(r[0][0]/(r[0][0]+r[1][0]))*100)
print("True Negative Rate (TNR) :",(r[1][1]/(r[1][1]+r[0][1]))*100)
print("False Negative Rate (FNR) :",(r[1][0]/(r[1][0]+r[0][0]))*100)
print("False Positive Rate (FPR) :",(r[0][1]/(r[0][1]+r[1][1]))*100)
x1=(classification_report(y_test,predictions))
print(x1)

accuracy: 93.56725146198829
True Positive Rate (TPR) : 99.07407407407408
True Negative Rate (TNR) : 84.12698412698413
False Negative Rate (FNR) : 0.9259259259259258
False Positive Rate (FPR) : 15.873015873015872
              precision    recall  f1-score   support

           0       0.99      0.91      0.95       117
           1       0.84      0.98      0.91        54

   micro avg       0.94      0.94      0.94       171
   macro avg       0.92      0.95      0.93       171
weighted avg       0.94      0.94      0.94       171



# Train Data with 10 Input Features

In [8]:
x=df.drop(['diagnosis_code','fractal_dimension_se','texture_se',],axis=1)
y=df.diagnosis_code

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=4,test_size=0.3)

sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

classifier=KNeighborsClassifier(n_neighbors=7,p=2,metric='euclidean')
classifier.fit(x_train,y_train)

predictions=classifier.predict(x_test)

r=confusion_matrix(y_test,predictions)
print(r)

[[106  11]
 [  2  52]]


In [9]:
print("accuracy:",accuracy_score(y_test,predictions)*100)
print("True Positive Rate (TPR) :",(r[0][0]/(r[0][0]+r[1][0]))*100)
print("True Negative Rate (TNR) :",(r[1][1]/(r[1][1]+r[0][1]))*100)
print("False Negative Rate (FNR) :",(r[1][0]/(r[1][0]+r[0][0]))*100)
print("False Positive Rate (FPR) :",(r[0][1]/(r[0][1]+r[1][1]))*100)
x1=(classification_report(y_test,predictions))
print(x1)

accuracy: 92.39766081871345
True Positive Rate (TPR) : 98.14814814814815
True Negative Rate (TNR) : 82.53968253968253
False Negative Rate (FNR) : 1.8518518518518516
False Positive Rate (FPR) : 17.46031746031746
              precision    recall  f1-score   support

           0       0.98      0.91      0.94       117
           1       0.83      0.96      0.89        54

   micro avg       0.92      0.92      0.92       171
   macro avg       0.90      0.93      0.92       171
weighted avg       0.93      0.92      0.93       171



# Train Data with 11 Input Features

In [10]:
x=df.drop(['diagnosis_code','fractal_dimension_se'],axis=1)
y=df.diagnosis_code

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=4,test_size=0.3)

sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

classifier=KNeighborsClassifier(n_neighbors=7,p=2,metric='euclidean')
classifier.fit(x_train,y_train)

predictions=classifier.predict(x_test)

r=confusion_matrix(y_test,predictions)
print(r)

[[108   9]
 [  3  51]]


In [11]:
print("accuracy:",accuracy_score(y_test,predictions)*100)
print("True Positive Rate (TPR) :",(r[0][0]/(r[0][0]+r[1][0]))*100)
print("True Negative Rate (TNR) :",(r[1][1]/(r[1][1]+r[0][1]))*100)
print("False Negative Rate (FNR) :",(r[1][0]/(r[1][0]+r[0][0]))*100)
print("False Positive Rate (FPR) :",(r[0][1]/(r[0][1]+r[1][1]))*100)
x1=(classification_report(y_test,predictions))
print(x1)

accuracy: 92.98245614035088
True Positive Rate (TPR) : 97.2972972972973
True Negative Rate (TNR) : 85.0
False Negative Rate (FNR) : 2.7027027027027026
False Positive Rate (FPR) : 15.0
              precision    recall  f1-score   support

           0       0.97      0.92      0.95       117
           1       0.85      0.94      0.89        54

   micro avg       0.93      0.93      0.93       171
   macro avg       0.91      0.93      0.92       171
weighted avg       0.93      0.93      0.93       171



# Train Data with 12 Input Features

In [12]:
x=df.drop(['diagnosis_code'],axis=1)
y=df.diagnosis_code

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=4,test_size=0.3)

sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

classifier=KNeighborsClassifier(n_neighbors=7,p=2,metric='euclidean')
classifier.fit(x_train,y_train)

predictions=classifier.predict(x_test)

r=confusion_matrix(y_test,predictions)
print(r)

[[110   7]
 [  3  51]]


In [13]:
print("accuracy:",accuracy_score(y_test,predictions)*100)
print("True Positive Rate (TPR) :",(r[0][0]/(r[0][0]+r[1][0]))*100)
print("True Negative Rate (TNR) :",(r[1][1]/(r[1][1]+r[0][1]))*100)
print("False Negative Rate (FNR) :",(r[1][0]/(r[1][0]+r[0][0]))*100)
print("False Positive Rate (FPR) :",(r[0][1]/(r[0][1]+r[1][1]))*100)
x1=(classification_report(y_test,predictions))
print(x1)

accuracy: 94.15204678362574
True Positive Rate (TPR) : 97.34513274336283
True Negative Rate (TNR) : 87.93103448275862
False Negative Rate (FNR) : 2.6548672566371683
False Positive Rate (FPR) : 12.068965517241379
              precision    recall  f1-score   support

           0       0.97      0.94      0.96       117
           1       0.88      0.94      0.91        54

   micro avg       0.94      0.94      0.94       171
   macro avg       0.93      0.94      0.93       171
weighted avg       0.94      0.94      0.94       171



# Train Data with 9 Input Features (When n_neighbors=9)

In [14]:
x=df.drop(['diagnosis_code','fractal_dimension_se','symmetry_se','texture_se'],axis=1)
y=df.diagnosis_code

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=4,test_size=0.3)

sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

classifier=KNeighborsClassifier(n_neighbors=9,p=2,metric='euclidean')
classifier.fit(x_train,y_train)

predictions=classifier.predict(x_test)

r=confusion_matrix(y_test,predictions)
print(r)

[[108   9]
 [  2  52]]


In [15]:
print("accuracy:",accuracy_score(y_test,predictions)*100)
print("True Positive Rate (TPR) :",(r[0][0]/(r[0][0]+r[1][0]))*100)
print("True Negative Rate (TNR) :",(r[1][1]/(r[1][1]+r[0][1]))*100)
print("False Negative Rate (FNR) :",(r[1][0]/(r[1][0]+r[0][0]))*100)
print("False Positive Rate (FPR) :",(r[0][1]/(r[0][1]+r[1][1]))*100)
x1=(classification_report(y_test,predictions))
print(x1)

accuracy: 93.56725146198829
True Positive Rate (TPR) : 98.18181818181819
True Negative Rate (TNR) : 85.24590163934425
False Negative Rate (FNR) : 1.8181818181818181
False Positive Rate (FPR) : 14.754098360655737
              precision    recall  f1-score   support

           0       0.98      0.92      0.95       117
           1       0.85      0.96      0.90        54

   micro avg       0.94      0.94      0.94       171
   macro avg       0.92      0.94      0.93       171
weighted avg       0.94      0.94      0.94       171



# Train Data with 9 Input Features (When n_neighbors=11)

In [16]:
x=df.drop(['diagnosis_code','fractal_dimension_se','symmetry_se','texture_se'],axis=1)
y=df.diagnosis_code

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=4,test_size=0.3)

sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

classifier=KNeighborsClassifier(n_neighbors=11,p=2,metric='euclidean')
classifier.fit(x_train,y_train)

predictions=classifier.predict(x_test)

r=confusion_matrix(y_test,predictions)
print(r)

[[110   7]
 [  0  54]]


In [17]:
print("accuracy:",accuracy_score(y_test,predictions)*100)
print("True Positive Rate (TPR) :",(r[0][0]/(r[0][0]+r[1][0]))*100)
print("True Negative Rate (TNR) :",(r[1][1]/(r[1][1]+r[0][1]))*100)
print("False Negative Rate (FNR) :",(r[1][0]/(r[1][0]+r[0][0]))*100)
print("False Positive Rate (FPR) :",(r[0][1]/(r[0][1]+r[1][1]))*100)
x1=(classification_report(y_test,predictions))
print(x1)

accuracy: 95.90643274853801
True Positive Rate (TPR) : 100.0
True Negative Rate (TNR) : 88.52459016393442
False Negative Rate (FNR) : 0.0
False Positive Rate (FPR) : 11.475409836065573
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       117
           1       0.89      1.00      0.94        54

   micro avg       0.96      0.96      0.96       171
   macro avg       0.94      0.97      0.95       171
weighted avg       0.96      0.96      0.96       171

